spring:
  application:
    name: Pause Clope
  data:
    rest:
      base-path: /api/v1

  datasource:
    url: jdbc:postgresql://localhost:5432/cookieclicker
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or 'none', 'create', 'create-drop', 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
